server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: decision-service
  datasource:
    url: jdbc:postgresql://localhost:5432/evidentor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  grpc:
    server:
      port: 9092
      reflection:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
debug: false
